trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '20.x'
  displayName: 'Install Node.js'

- script: |
    npm install
    npm run build  # Ensure "build" exists in your package.json
  displayName: 'npm install and build'

- script: |
    npx playwright install
  displayName: 'Install Playwright browsers'

- script: |
    npx playwright test --reporter=junit --output=./test-results  # Configure for JUnit output
  displayName: 'Run Playwright tests'
  continueOnError: true

- task: PublishTestResults@2
  inputs:
    testResultsFormat: 'JUnit'
    testResultsFiles: '**/test-results/*.xml'
    failTaskOnFailedTests: true

- task: PublishPipelineArtifact@1
  inputs:
    targetPath: '$(Pipeline.Workspace)'
    artifactName: 'playwright-report'
    publishLocation: 'pipeline'
