trigger:
  branches:
    include:
      - main
      - master

pr:
  branches:
    include:
      - main
      - master

jobs:
- job: Test
  timeoutInMinutes: 60
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - script: |
      sudo apt-get update
      sudo apt-get install -y nodejs npm
    displayName: 'Install Node.js and npm'
  - script: npm ci
    displayName: 'Install dependencies'
  - script: npx playwright install --with-deps
    displayName: 'Install Playwright Browsers'
  - script: npx playwright test
    displayName: 'Run Playwright tests'
  - task: PublishPipelineArtifact@1
    inputs:
      targetPath: 'playwright-report/'
      artifact: 'playwright-report'
      publishLocation: 'pipeline'
    displayName: 'Publish Playwright report'
