name: Playwright Tests
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
jobs:
  build-and-test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      # Checkout code
      - uses: actions/checkout@v4

      # Set up Node.js environment
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*

      # Install dependencies
      - name: Install Dependencies
        run: npm install

      # Install Playwright browsers
      - name: Install Playwright Browsers
        run: npx playwright install
        
      # Install Allure CLI
      - name: Install Allure CLI
        run: |
          wget -q https://github.com/allure-framework/allure2/releases/download/2.21.0/allure-commandline-2.21.0.zip -O allure-commandline.zip
          unzip -o allure-commandline.zip -d /opt/allure
          export PATH="/opt/allure/bin:$PATH"

      # Run tests with Allure reporting
      - name: Run Tests
        env:
          LOGIN_URL: ${{ secrets.LOGIN_URL }}
          LOGIN_PASSWORD_SECONDARY: ${{ secrets.LOGIN_PASSWORD_SECONDARY }}
          LOGIN_EMAIL1: ${{ secrets.LOGIN_EMAIL1 }}
          LOGIN_PASSWORD1: ${{ secrets.LOGIN_PASSWORD1 }}
          LOGIN_EMAIL: ${{ secrets.LOGIN_EMAIL }}
          LOGIN_PASSWORD: ${{ secrets.LOGIN_PASSWORD }}
          MY_APPLICATION_URL: ${{ secrets.MY_APPLICATION_URL }}
        run: |
          npm run test
          npm run allure:generate

      # Generate and Upload Allure Results
      - name: Upload Allure Results
        uses: actions/upload-artifact@v4
        with:
          name: allure-results
          path: allure-results/
